oras-project/rust-oci-client

- .github/workflows/build.yml
- Cargo.lock
- Cargo.toml
- deny.toml
- src/client.rs
- src/lib.rs
- src/www_authenticate/README.md
- src/www_authenticate/mod.rs
Needed to fix the `chrono`-related security issues - hyperx 0.13 was released back in January 2019.
Note: this is pending a change upstream to be [merged for hyperx 1.3 support](https://github.com/KeenS/www-authenticate/pull/5). Once that's merged I can stop cargo from pointing at my local git repository, which is necessary to publish oci-distribution.
> bump to hyperx 1.3

- src/client.rs
This settings depends on the SSL backend, and is only applicable if
the openssl native backend is used.
> Make accept_invalid_hostnames conditional

- src/client.rs
- src/token_cache.rs
The GitHub container registry (ghcr.io) returns a bearer token that doesn't have an explicit expiration time.
Prior to this change, because of this anomaly, the token was not added into the JWT token cache. That caused all the request done against ghcr.io to be unauthenticated. That broke any kind of interaction with ghcr, even with public images.
This code handles the lack of an expiration claim by setting a 60 second expiration window.
According to [the official documentation](https://docs.docker.com/registry/spec/auth/token/#requesting-a-token), this behaviour is fine:
> The duration in seconds since the token was issued that it will remain valid.
> When omitted, this defaults to 60 seconds. For compatibility with older clients,
> a token should never be returned with less than 60 …
> Fix interacting with GitHub Container Registry

- deny.toml
Specify which license is used by the `encoding_rs` crate, this is required to fix the cargo deny checks.
Fixes https://github.com/krustlet/oci-distribution/issues/13
> Fix the cargo deny failure

- CODEOWNERS
- Cargo.toml
Version bump to `0.8.1`
Tag a new release of oci-distribution. This is a patch release that contains the following fixes:
* `ClientConfig`: define `accept_invalid_hostnames` attribute only when `native-tls` is being used
* Improve parsing of container image names: this ensure `Reference` behaves in the same way as native Go libraries do when parsing oci names
* Fix interactions with GitHub Container Registry: ensure anonymous operations (like `pull`) can be performed
The following cleanups have been done:
* Remove `Cargo.lock` file from repository
* Remove the in-tree version of the `www-authenticate` crate: use the latest official release of it, which contains all the changes and fixes oci-distribution did.
* Fix all clippy warnings
* Fix `cargo deny` execution
> Prepare `0.8.1` release

- src/client.rs
We pass a list of accepted MIME types when pulling manifests, but then we immediately reject anything other than `application/vnd.docker.distribution.manifest.v2+json` when validating the response on:
https://github.com/krustlet/oci-distribution/blob/0e5373e99c910ffd1261ace7e1b732036dc7784a/src/client.rs#L548
This change removes the list type which we are incapable of parsing. As a result, registries which can serve manifest lists (like DockerHub) will return a single manifest instead (presumably for `amd64`?). If we have a strong opinion in the future about which manifest to use from the list, we can implement proper parsing for these manifest lists.
> Remove manifest list from MIME Accept header

- src/client.rs
- src/manifest.rs
- src/reference.rs
This PR is an initial attempt to add support for manifest lists. (I wasn't sure whether to submit to here or krustlet/krustlet, so just picked here)
The approach I've gone for is:
- add OciImageIndexManifest struct representing an image manifest
- rename existing OciManifest to OciImageManifest
- create OciManifest enum wrapping the Image and Image Index manifest
- users can specify how a client behaves when it receives an image index manifest via the platform_resolver field
- by default the client attempts to select an image from the image index manifest that matches the running platform
- the exception is the pull_manifest function - if someone is just pulling a manifest then they should get the manifest as it is in the registry
- I've added a pull_image_manifest function which does …
> Add support for manifest list/image index manifest

- src/client.rs
Two minor fixes, each one living inside of its dedicated commit.
* Client: do not fail when a OCI manifest is found. The library is able to handle OCI manifests, hence it should not report an error when one is found.
* Fix usage of Client behind dynamic reference. Be explicit about the traits supported by the platform resolver function. This is needed to use the Client behind a dynamic reference, something similar to what is described [here](https://users.rust-lang.org/t/how-to-send-function-closure-to-another-thread/43549)
> Minor fixes

- src/client.rs
This change maintains the previous behaviour on Windows, but I'mt not
sure that is correct to be fair, and I suspect we only need:
`#[cfg(feature = "native-tls")]`
> fix: Allow build with feature `rustls-tls`

- Cargo.toml
- src/client.rs
- src/manifest.rs
I've been trying to use this crate to pull images from one registry and push them to another - I've fixed a few issues I encountered, and added a test for roundtrip pull/pushing an image with multiple layers.
The existing push doesn't work for images with multiple layers because the code conflates chunks and layers. e.g it starts a push session for ImageData, then proceeds to push all the layers as chunks in a single blob.
I've updated this to have a push session per layer, per the spec.
The push response for `Client::push` similarly doesn't return an image_url, as that
doesn't make sense for images with multiple layers.
The ImageData struct no longer produces a digest from the contained
layers as digests are applicable to content blobs, or manifests.
If the manifest being pushed has a …
> Fix various with image pushes.

- src/client.rs
- src/lib.rs
Export pull_blob API
1. Container images will share layers, the API should support the scenario which don't need pull all the layers.
2. Container image size may vary from megabyte to gigabyte, export pull_layer API can allow the user to the following layer decompress/unpack/store operations in parallel.
Export auth API
For some container image service which support ondemand layer pull like:
* stargz https://github.com/containerd/stargz-snapshotter
* Nydus Image Service https://github.com/dragonflyoss/image-service
export auth API is a requirement when token is expired.
> Export pull_layer & auth API

- src/client.rs
it previously calculated the digest of the image layers, by taking a digest of all the layers data. This calculation is not used in the OCI registry API, nor is the digest of an image.
(I intended to make this change in https://github.com/krustlet/oci-distribution/pull/22, as described in that PR description, but I didn't actually make the change...)
> Remove digest calculation of ImageData

- Cargo.toml
- examples/get-manifest/main.rs
- src/client.rs
- src/manifest.rs
This PR is based on https://github.com/krustlet/oci-distribution/pull/26. These are the changes done on top of what has been provided by @jsoverson:
* Rebase against `main` and fix the conflicts
* `OciManifest`: do not implement `Display` by serializing to JSON all the structs. This change was requested by @thomastaylor312 and @bacongobbler 
* Provide a simple example program that can be used to get an OCI manifest and display it on the stdout
> Push manifest list rebase and feedback addressed

- Cargo.toml
- src/client.rs
- src/errors.rs
- src/reference.rs
Define a custom Error type and return that inside of all the public APIs. Returning `anyhow::Result` is no longer done.
This makes possible, for consumers of the library, to implement better error handling.
Fixes https://github.com/krustlet/oci-distribution/issues/28
~~Note well: this is built on top of https://github.com/krustlet/oci-distribution/pull/26~~
~~Note well: this is built on top of https://github.com/krustlet/oci-distribution/pull/32~~
Update: rebased against `main`
> Provide custom errors

- Cargo.toml
- examples/pull-wasm/main.rs
- examples/wasm/cli.rs
- examples/wasm/main.rs
- examples/wasm/pull.rs
- examples/wasm/push.rs
- src/client.rs
- src/errors.rs
Workaround push issues affecting AWS ECR
It seems AWS ECR is not respecting the OCI Distribution Spefication about:
* Push blobs as chunks: successful chunk uploads have return code 201 instead of 202
* Push Manifest: successful response is missing the `Location` header
This PR tries to work around this limitations, until the issues are sorted out by AWS.
These are the mitigations used.
* Wrong response with chunked uploads: when a spec violation is found, attempt the upload using the monolithic approach. ECR is respecting the spec in that regard.
* Missing `Location` header after manifest upload: given the whole image is already inside of the remote registry, we calculate the `Location` value by using the digest of the manifest. This is the value that is expect to be returned by the …
> Workaround AWS ECR issues

- Cargo.toml
Changes since 0.8.1:
* Add support for manifest list and image index manifest types
* Fix: address Windows incompatibility issues
* [API breaking] Change the API of `Client::push`: return also the manifest digest
* Fix: do not fail when an OCI manifest is returned. The library can handle them too
* Fix: Be explicit about the traits supported by the platform resolver function. This is needed to use the Client behind a dynamic reference.
* [API breaking] Fix: pushing of images with multiple layers now works
* Enhancement: ensure the manifest pushed are using canonicalized JSON
* Enhancement: improve test suite by performing certain operations against a real container registry
* Enhancement: export the `pull_layer` and the auth APIs
* Enhancement: support of pushing manifest lists
* [API …
> Prepare 0.9.0 release

- Cargo.toml
* Fix: ensure layers bigger than 4Mb can be pushed (issue https://github.com/krustlet/oci-distribution/issues/35)
> Release v0.9.1

- Cargo.toml
- deny.toml
- src/client.rs
- src/errors.rs
Add options to oci-distrobution to use
non local DNS, mainly for when
running embedded in a docker container.
> Allow to use trust-dns

- src/client.rs
Fix one of our unit test that suddenly started to fail.
The test was doing to following operations:
1. Start local OCI registry configured to require authentication
2. Pull a wasm module from the public Azure Container Registry
3. Push the wasm module into the local OCI registry
The test was using the local OCI registry credentials to authenticate against the Azure Container Registry. This was not needed because the module being pulled is public, hence no auth is required. Something changed with regards to Azure CR, which started to reject our authentication efforts.
The test has been changed to perform an anonymous pull from Azure CR.
> fix: address broken test

- Cargo.toml
Expose a feature of the reqwest crate that allows to use the system certificates.
> fix: rustls allow usage or system root certificates

- Cargo.toml
- src/client.rs
- src/config.rs
- src/lib.rs
Related to https://github.com/krustlet/oci-distribution/issues/50, added structure definitions.
> feat: Add OCI Image Configuration structures

- Cargo.toml
- src/client.rs
Most of the dependencies like reqwest already handle compilation for wasm32, so it is a matter of setting only the supported tokio features and guard some of the reqwest APIs that are not supported on wasm32.
The underlying motivation is to use sigstore on wasm32 architectures, but being able to work with OCI registries from WASM modules might come in handy as well.
> Add support for compiling to wasm32 architecture

- src/client.rs
Manifests list feature in `oci-distribution` is already implemented, default image in docker.io like busybox use `IMAGE_MANIFEST_LIST_MEDIA_TYPE`, but ubuntu image use `OCI_IMAGE_INDEX_MEDIA_TYPE`.
Fixes: #27
> client: Fix failed to pull ubuntu image from docker.io

- src/errors.rs
The visibility of the registry error code (`OciErrorCode`) is `pub`, but there is no way to use it because the visibility of `OciEnvelop.errors` is `pub(crate)`.
> Change the visibility of `OciEnvelop.errors` to `pub`

- src/reference.rs
This commit updates the default endpoint for DockerHub to be
`index.docker.io`. This is the default endpoint that the Docker CLI is
using.
Running `docker info`, this is the endpoint returned for the registry:
```
$ docker info | grep Registry
Registry: https://index.docker.io/v1
```
This means we can now push references to
`index.docker.io/user/repo:tag`.
Signed-off-by: Radu Matei <radu.matei@fermyon.com>
> Update default `docker.io` registry

- src/client.rs
I just ran into an issue exacerbated by a load balancer where the initial pull would succeed, but subsequent layer pulls would fail and return 0-bytes for random layers.
Turns out that using `request.byte_stream()` (or `request.bytes()`) will succeed regardless of HTTP status, so error responses would still "succeed" with no data returned.
This PR turns non-success responses into errors.
> Fix: Expose HTTP errors when pulling layers

- Cargo.toml
- src/client.rs
Return Stream and allow the user to decide how to use it.
Move dependency of `tokio-util` to dev for tests.
Fixes: #58
> client: Return Stream for async_pull_blob API

- deny.toml
Address the warnings produced by cargo deny.
Warning: I set cargo deny to allow duplicate versions of the same crate to be used. @thomastaylor312, @bacongobbler are you fine with that?
> fix(CI): address warnings of cargo deny

- src/client.rs
The rust target arch for `ppc64le` is `powerpc64`.  However, while resolving the platform for an image, consider it as `ppc64le`.
> consider ARCH as ppc64le when rust arch is powerpc64

- src/manifest.rs
Add an optional `artifactType` field to the image manifest to reflect the new changes for OCI v1.1.
See: https://github.com/opencontainers/image-spec/blob/main/manifest.md#image-manifest
> add optional artifactType to image manifest for oci v1.1

- src/client.rs
Workaround to a known issue of rustc: <https://github.com/rust-lang/rust/issues/104382>.
I encountered this issue when using this library with <https://github.com/seanmonstar/warp>. The error propagated from `oci-distribution` into my crate, outputting two hundred lines of error messages. Here is the horrible error messages from my project (<https://github.com/linyinfeng/oranc/pull/24/commits/d9076872dbb26a39d167ddff88cd9e04df44a7d4>, [cargo.log](https://github.com/krustlet/oci-distribution/files/12319923/cargo.log)).
After some bisect, debug, and search, I found that it is a known issue of rustc, and the workaround is simple.
> Higher-ranked lifetime error workaround

- src/client.rs
- src/config.rs
- src/manifest.rs
* Added Media Type Extraction to OciManifest.content_type() to facilitate pushing of Docker Images
* Updated push_manifest to be public cause i believe that its generally useful for library consumers. [Usage Example](https://gitlab.com/rbbl/devops-tools/semtag/-/blob/main/src/main.rs?ref_type=heads)
> Improved Push Logic

- src/client.rs
- src/errors.rs
This PR implements the TryFrom for a client::Config so that it can be parsed back into a ConfigFile.
This feature is useful when pulling images from a registry, so that the metadata recieved can be viewed.
> Conversion between a Config and a ConfigFile

- src/client.rs
- src/errors.rs
This is a rebased version of #63, which was automatically closed due to the history rewrite. I have addressed the PR feedback (see [here](https://github.com/krustlet/oci-distribution/pull/63#discussion_r1120745561) and [here](https://github.com/krustlet/oci-distribution/pull/63#discussion_r1122810246) for more info).
> Enhance client to push blobs, mount blobs, and push raw manifests

- src/client.rs
Bring back the workaround required to circumvent https://github.com/rust-lang/rust/issues/104382
This was accidentally removed with 1c511f28c3338683162cb1f20ef218beb814ac65
CC @linyinfeng
> fix: bring back workaround for rustc

- Cargo.toml
The crate version was already bumped. We never released 0.10, hence there's no need to jump straight from 0.9 to 0.11.
> Fix crate version: 0.11 -> 0.10

- src/client.rs
- src/token_cache.rs
Hey all!
Thanks for the great crate.
I'm starting a new project that relies heavily on it, and noticed that `Client` isn't `Clone` for no apparent reason - adding it is easy and enables users to concurrently work with it ;)
> client is now clonable and can be used in concurrent manner

- examples/get-manifest/main.rs
- src/client.rs
- src/token_cache.rs
Sorry about the spam!
This builds upon the other 2 PRs #109  #110 
Just out of comfort assuming if merged I'll work on it serially.
This adds logic to enable token re-creation when needed, and also making the auth API more fluent.
I had a situation where my token got expired mid-upload and there was no place to renew, and if I could break the API I'd have structured it a bit different, but I think is ok.
> Refactor auth - add re-auth mechanism

- src/client.rs
- src/errors.rs
Implements `Client::pull_manifest_raw` for fetching the plain text representation of a manifest without deserializing it into an `OciManifest`.
This way the manifest can be pushed elsewhere while maintaining the digest value of the manifest which is otherwise subject to change following re-serialization of the `OciManifest` object.
`push_manifest_raw` takes a `Vec<u8>`, while `pull_manifest_raw` returns the content as a `String`. I've chosen this route, since it allows us to still call `validate_registry_response` in `Client::_pull_manifest_raw` where the response status and manifest text is available for validation.
Since `pull_manifest_raw` is specifically intended for fetching individual manifests for mirroring, I expect the caller to be traversing the tree of manifests manually and …
> Implement Client::pull_manifest_raw

- Cargo.toml
It has been a while since we published the last release. I think it's time for another minor release.
We have to do a minor release, instead of a patch one, because we introduced some breaking changes in the API.
- client is now clonable and can be used in concurrent manner by @aviramha in https://github.com/krustlet/oci-distribution/pull/109
- fix(\*): Fixes our use of deprecated functions by @thomastaylor312 in https://github.com/krustlet/oci-distribution/pull/113
- Pull alternative urls by @seanyoung in https://github.com/krustlet/oci-distribution/pull/108
- Refactor auth - add re-auth mechanism by @aviramha in https://github.com/krustlet/oci-distribution/pull/111
- Implement Client::pull_manifest_raw by @MathiasPius in https://github.com/krustlet/oci-distribution/pull/115
- …
> Tag 0.11 release

- src/client.rs
- src/token_cache.rs
- Updates to allow configuration of the default token expiration value, via ClientConfig
Open to suggestions on how best to pipe this through where it needs to be.  I noticed `TokenCache` no longer has a `new()` function, hence the creation of `TokenCache::default()` and then amending the attribute.
> feat(client/token_cache): allow configuration of default token expiration

- Cargo.toml
- examples/wasm/main.rs
- examples/wasm/push.rs
- src/client.rs
- src/manifest.rs
- Update ImageLayer to derive Debug, Eq, Hash and PartialEq traits
- **_Breaking_**: Convert annotations from a HashMap to a BTreeMap per https://github.com/krustlet/oci-distribution/pull/121#discussion_r1544777159, so that we don't need a custom Hash impl for ImageLayer
Changeset motivated by the need to differentiate and deduplicate collections of ImageLayers.
> ref(client): Debug, Eq, Hash, PartialEq for ImageLayer; convert annotations to BTreeMap

- src/errors.rs
This now also allows to use the error structs defined in this crate to serialize with serde again.
> feat(errors): Allow to serialize errors with serde

- src/client.rs
The old `OciDescriptor` has too many fields, which maybe aren't available when trying to pull a blob with only the digest. In the past you only needed the digest as string, but the optional urls field was added (in #108). But all other fields of the `OciDescriptor` aren't required when pulling a blob, but are required by the struct. The `LayerDescriptor` struct now has only the fields which are used for pulling.
This is a breaking change, as it changes the signature of the pull methods. But with this it is now possible to pull a blob with only the digest as a `&str` again.
> Create new LayerDescriptor for pulling blobs

- Cargo.toml
- src/client.rs
Use latest version of testcontainers, fix the code to cope with the API changes.
> chore(deps): update to latest version of testcontainers

- deny.toml
After running a cargo update, some of the derive crates used by testcontainers (a dev dependency) are pulling in unicode parsing with the unicode-3.0 license which is the most recent.
As we already had a unicode exception in and since it is an OSI approved license, we should be ok here
> fix(deny): Fixes license issues with deny check

- Cargo.toml
- src/client.rs
Allow to set `read_timeout` and `connect_timeout` on the underlying client. Otherwise the pull will just hang forever if you have an unstable connection and there was an interruption.
I wasn't sure if it would be useful to set some defaults here, but decided against it, because there was no timeout before (so no change for existing implementations) and there is also no timeout set in the reqwest client by default. And I also wasn't sure what useful defaults would be (since that maybe depends on your connection?). But let me know if you want me to set a default value for these.
> feat(client): allow to set read_timeout and connect_timeout

- src/client.rs
I noticed that the client doesn't send a user-agent, so lets set the crate name/version by default but also allow others to overwrite it with their own app-name in the config.
> feat(client): allow to set the User-Agent used by the client

- src/client.rs
The main reason for this Pull-Request is to allow doing partial requests. This is a very useful feature if you have very slow/unstable internet (like in Germany) and the pull often fails for various reasons (timeout or other connection errors). So it doesn't help if you can download the first few MB of a blob over and over again before the network connection craps out after some minutes and you can start over again. If your upstream registry supports partial requests, you at least can pull the next few MB every time, and eventually get the whole blob.
I only added the streaming version of this function, as I didn't know how to handle it when giving a writer as parameter, as if the upstream registry doesn't support it, it will respond with a full response and there is no good way to signal …
> Partial Requests and some other pull refactorings

- src/client.rs
- src/reference.rs
This adds the ability to set a mirror to the `Reference` instance, which is then used to pull the image, instead of the registry that was parsed from the image name. And it then forwards the original registry with the `ns` query parameter to the mirror registry, so the mirror registry can use this information to decide from which registry you wanted to pull something.
This is currently not an officially documented standard feature yet, but it's probably going to be eventually, it's just taking a really long time (https://github.com/opencontainers/distribution-spec/pull/66). But containerd is already using the `ns` query parameter and I think I read somewhere that nexus is also already using the parameter when used as pull through cache (but I haven't verified that). But I think it's a …
> Add namespace query parameter for registry mirroring/proxying

- src/client.rs
This allows to store auth information to the client if needed, without doing a full auth request.
I have the use-case where I might pull a blob without pulling the manifest before, as there are multiple replicas and the manifest might have been pulled by another instance already. But that means that some instances never had the auth information stored and therefore the pull of the blob fails with a 401.
I know I could all `client.auth(...)`, but that also runs a full auth request (which even is multiple requests) every time, even if the auth info is already stored for this registry, or even when it's already authenticated for this image.
I also could keep track myself if I already authenticated for a certain registry, but that would be kinda redundant if the client already keeps track of …
> feat(client): Make store_auth_if_needed public

- Cargo.toml
- src/blob.rs
- src/client.rs
This impls a simple passthrough stream implementation for `SizedStream`. It also updates the doc to show how you can use the stream directly. Please note that although this is _technically_ an add by adding the impl Stream, it really just fixes some possibly annoying ergonomics. So I marked this as 0.12.1
Fixes #157
> fix(blob): Makes sure `SizedStream` impls `Stream`

- src/client.rs
This feature allows a client to pull images via a proxy. In some cases like intranet with a outgoing proxy it's very useful.
> client: add support to set https_proxy/no_proxy for client

- README.md
Looks like the crate has been re-published as `oci-client`. This pr updates the docs link in the readme.
> Docs.rs badge, update crate name.

- src/client.rs
Addresses https://github.com/oras-project/rust-oci-client/issues/162
> Allow doing start-end RANGE requests against blobs

- src/blob.rs
- src/client.rs
- src/manifest.rs
In #163 it was pointed out that we can't use validating streams for partial responses, which makes complete sense. Because of this, we need to pass back the digest header for use in validation once a partial download is complete.
This also fixes a few clippy errors I saw
> fix(client): Return the digest header for partial responses

- Cargo.toml
I've also updated the `Cargo.toml` metadata to show links to our docs.
- client: add support to set https_proxy/no_proxy for client by @Xynnn007 in https://github.com/oras-project/rust-oci-client/pull/160
- chore(deps): Update testcontainers requirement from 0.20 to 0.22 by @dependabot in https://github.com/oras-project/rust-oci-client/pull/161
- Docs.rs badge, update crate name. by @bddap in https://github.com/oras-project/rust-oci-client/pull/166
- chore(deps): Bump actions/checkout from 4.1.7 to 4.2.0 by @dependabot in https://github.com/oras-project/rust-oci-client/pull/170
- chore(deps): Update testcontainers requirement from 0.22 to 0.23 by @dependabot in https://github.com/oras-project/rust-oci-client/pull/169
- chore(deps): Update rstest requirement from 0.22.0 to 0.23.0 by …
> Release 0.13.0

- src/client.rs
When testing this library against [Google Cloud Artifact Registry](https://cloud.google.com/artifact-registry/docs), I noticed the upload URL they return when obtaining a session id differs from the spec.
Instead of returning a `Location:` as specified in the OCI Distribution spec:
```
/v2/<name>/blobs/upload/<reference>
```
GCP Artifactory Registry returns the following `Location:` header:
```
/artifacts-uploads/namespaces/<gcp-project-id>/repositories/<artifact-registry-repository>/uploads/<some-hash>
```
I would like to propose relaxing the `location_header_to_url` code slightly to allow the use of this returned header, which does seem based to be on a perhaps slightly "looser interpretation" of [what the spec says under `POST then …
> feat: Relax location_header_to_url path handling

- src/client.rs
Following up on #175 and #176, this rounds out the remaining set of functionality that's needed to use `rust-oci-client` for pushing to GCP Artifact Registry similarly to how `oras-go` can be used for this.
This seemed like an option that should be available for configuring the client in case you're working with a registry that's not fully spec compliant.
> feat: Add option for using monolithic push

- src/manifest.rs
As seen [here](https://github.com/opencontainers/image-spec/blob/main/image-index.md#image-index-property-descriptions), this optional field can sometimes be present.
> Add artifactType to OciImageIndex

- src/errors.rs
- src/manifest.rs
This allows creating accessory artifacts that can be associated with artifacts in a repository. Additionally added a missing error code.
> Add subject to OciImageManifest

- Cargo.toml
- deny.toml
- src/client.rs
This updates our deny.toml to remove unused exceptions and change which unicode license is being allowed. I also fixed a small clippy error that showed up
> chore: Updates thiserror and fixes cargo deny

- src/client.rs
- src/secrets.rs
Adds RegistryAuth::Bearer for use of direct bearer token authentication
> feat: Direct Bearer Token Authentication

- src/client.rs
This commit adds one more configuration for client about proxy, s.t. http_proxy. http_proxy sets the http proxy that the client uses to pull images, while no_proxy will define the remote address that will not be accessed by proxy.
This is useful in a local registry scenario where original pull request is in http.
Typical https_proxy looks like `http://127.0.0.1:5432` no_proxy looks like `127.0.0.1,192.168.1.1`
Note that `client_builder.proxy()` function will add rather than overwrite the proxies to underlying reqwest::Client, thus no side effections upon the https proxy setting.
> feat: add HTTP proxy for client

- Cargo.toml
Prepare new release, fixes https://github.com/oras-project/rust-oci-client/issues/197
- Add artifactType to OciImageIndex by @rylev in https://github.com/oras-project/rust-oci-client/pull/182
- chore(deps): Bump actions/checkout from 4.2.1 to 4.2.2 by @dependabot in https://github.com/oras-project/rust-oci-client/pull/183
- Add subject to OciImageManifest by @fibonacci1729 in https://github.com/oras-project/rust-oci-client/pull/181
- chore: Updates thiserror and fixes cargo deny by @thomastaylor312 in https://github.com/oras-project/rust-oci-client/pull/185
- chore(deps): Update itertools requirement from 0.13.0 to 0.14.0 by @dependabot in https://github.com/oras-project/rust-oci-client/pull/188
- chore(deps): Update rstest requirement from 0.23.0 to 0.24.0 by @dependabot in …
> release: prepare 0.15.0 release

- src/client.rs
Good morning/afternoon!
This is an attempt at upstream some of the changes I've been carrying for this crate!
This adds a `push_blob_stream` method to the client that takes a stream as input. It's pretty much the same code as the chunked push method, except it just takes data until there's none left. Its signature is such that one can just use the stream from the streaming pull blob method.
It also adds a method that verifies if a blob exists. Combined with the streaming push method, it's quite handy to easily copy a bunch of blobs between two repositories.
Let me know if you see a need to split this into two pull requests or anything else.
I'll add an example and maybe a test if it's required!
> add push blob async stream support

- examples/get-manifest/main.rs
- examples/wasm/main.rs
- examples/wasm/pull.rs
- examples/wasm/push.rs
- src/blob.rs
- src/client.rs
- src/manifest.rs
- tests/digest_validation.rs
This is a breaking change, but modifies the API so anything that would be chunks of data we send (so blobs and the config data) is now a `Bytes`. That means any cloning of data is in the user's hands as they control how they construct the `Bytes`. We only clone bytes, which is cheap and doesn't clone the underlying data. The one exception that I didn't change to `Bytes` is `pull_manifest_raw` that returns a `Vec<u8>` since that is often handled in memory anyway. For consistency, we can change that to return `Bytes` as well if we'd like
Also includes some clippy fixes that will start erroring in the latest version of rust
This is followup to discussion we had in #204
> refactor(client)!: Reduces allocations of streaming data

- Cargo.toml
- src/client.rs
- src/token_cache.rs
https://github.com/oras-project/rust-oci-client/issues/167 suggests moving away from `jwt` because it's not actively maintained. These changes replace `jwt` with `jsonwebtoken`.
> chore: replace jwt with jsonwebtoken
